// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP5vx-B4SkjdomKZEHVPfTEfgNNbHC9Rc',
    appId: '1:863477971005:web:216dd7179843f331491254',
    messagingSenderId: '863477971005',
    projectId: 'cook-app-backend',
    authDomain: 'cook-app-backend.firebaseapp.com',
    storageBucket: 'cook-app-backend.firebasestorage.app',
    measurementId: 'G-42ZL3BXMS1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsDzSuRbgI54Z68POF_85jiF9MwDz1fBM',
    appId: '1:863477971005:android:d1c4822f7cdccedb491254',
    messagingSenderId: '863477971005',
    projectId: 'cook-app-backend',
    storageBucket: 'cook-app-backend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKyb-J2c9BPdZp3aoiWrPfw9cDJ0UNr_U',
    appId: '1:863477971005:ios:c4448433a8d66e6a491254',
    messagingSenderId: '863477971005',
    projectId: 'cook-app-backend',
    storageBucket: 'cook-app-backend.firebasestorage.app',
    iosBundleId: 'com.example.cookApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKyb-J2c9BPdZp3aoiWrPfw9cDJ0UNr_U',
    appId: '1:863477971005:ios:c4448433a8d66e6a491254',
    messagingSenderId: '863477971005',
    projectId: 'cook-app-backend',
    storageBucket: 'cook-app-backend.firebasestorage.app',
    iosBundleId: 'com.example.cookApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP5vx-B4SkjdomKZEHVPfTEfgNNbHC9Rc',
    appId: '1:863477971005:web:76e066f2e1c62482491254',
    messagingSenderId: '863477971005',
    projectId: 'cook-app-backend',
    authDomain: 'cook-app-backend.firebaseapp.com',
    storageBucket: 'cook-app-backend.firebasestorage.app',
    measurementId: 'G-MMW08SJNH0',
  );
}
